name: workflow-build-test-deploy
on:
  pull_request:
    branches:
      - "master"
  push:
    branches:
      - "master"
    tags:
      - "v*.*.*"
jobs:
  job-build-test:
    runs-on: ubuntu-latest
    steps:
    - name: "step-checkout"
      uses: actions/checkout@v1
    - name: "step-log"
      run: |
        echo "[D] job-build-test: github.ref: ${{github.ref}}"
  job-deploy:
    runs-on: ubuntu-latest
    needs:
      - job-build-test
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
    - name: "step-checkout"
      uses: actions/checkout@v1
    - name: "step-log"
      run: |
        echo "[D] job-deploy: github.ref: ${{github.ref}}"
